apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookify-webapp-deployment
  labels:
    app: bookify
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookify
  template:
    metadata:
      labels:
        app: bookify
    spec:
      containers:
      - name: bookify
        image: bookify:latest
        imagePullPolicy: Never 
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: bookify-webapp-service
spec:
  selector:
    app: bookify
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30001
  type: NodePort
